name: Publish ROCK
on:
  push:
    branches:
      - '*.*-[0-9]+.[0-9]+'
  workflow_dispatch:
    branches:
      - '*.*-[0-9]+.[0-9]+'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker
      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
      - name: Install yq
        run: |
          sudo snap install yq
      - uses: actions/download-artifact@v3
        with:
          name: rock-artifact
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push image to GHCR
        run: |
          app=$(yq .name rockcraft.yaml)
          version=$(yq '(.version|split("-"))[0]' rockcraft.yaml)
          base=$(yq '(.base|split(":"))[1]' rockcraft.yaml)
          tag=${version}-${base}_edge
          sudo skopeo --insecure-policy copy \
            oci-archive:${app}_${tag}_amd64.rock \
            docker-daemon:ghcr.io/canonical/${app}:${tag}
          docker push ghcr.io/canonical/${app}:${tag}
